apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sample-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd


--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-provisioner
  annotations:
    volume.beta.kubernetes.io/storage-class:
      sample-storageclass
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
