apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-vlsdisk-suitecrm-app
spec:
  selector:
    matchLabels:
      type: gce-pv
    matchExpressions:
      - {key: environment,operator:  In, values: [stg]}
  accessModes:
  - ReadWriteOnce
  storageClassName: manual


---


apiVersion: v1
kind: Pod
metadata:
  name: sample-pvc-pod
  labels:
    name: sample-pvc-pod
spec:
  containers:
  - name: sample-pvc-pod
    image: nginx:latest
    volumeMounts:
      - name: vol
        mountPath: "/usr/share/nginx/html"
    ports:
      - containerPort: 80
  volumes:
    - name: nginx-pvc
      PersistentVolumeClaim:
        claimName: sample-pvc
    
